import { useMemo } from 'react';
import { StyleSheet } from 'react-native';

import { useAppTheme } from '@/hooks/use-app-theme';
import { appThemes, type AppTheme } from '@/theme/appTheme';

export function useBudgetStyles() {
  const theme = useAppTheme();

  return useMemo(() => createBudgetStyles(theme), [theme]);
}

export const styles = createBudgetStyles(appThemes.dark);

function createBudgetStyles(theme: AppTheme) {
  return StyleSheet.create({
  screen: { backgroundColor: theme.screen, flex: 1 },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 54,
  },
  title: { color: theme.text, fontSize: 18, fontWeight: '800' },
  headerAddButton: {
    alignItems: 'center',
    backgroundColor: theme.primary,
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  headerAddText: { color: theme.textInverse, fontSize: 26, fontWeight: '500', lineHeight: 29 },
  headerSpacer: { width: 36 },
  periodTabs: {
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    marginTop: 22,
  },
  periodTabButton: { minWidth: 108 },
  periodTabButtonActive: { minWidth: 120 },
  periodTabActive: {
    borderBottomColor: theme.textSoft,
    borderBottomWidth: 2,
    color: theme.text,
    fontSize: 14,
    fontWeight: '800',
    paddingBottom: 12,
    paddingHorizontal: 18,
    minWidth: 120,
    textAlign: 'center',
  },
  periodTab: {
    color: theme.textSubtle,
    fontSize: 14,
    fontWeight: '800',
    minWidth: 108,
    paddingBottom: 12,
    paddingHorizontal: 18,
    textAlign: 'center',
  },
  loadingState: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  detailLoadingState: {
    alignItems: 'center',
    backgroundColor: theme.card,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 14,
  },
  emptyState: { alignItems: 'center', flex: 1, justifyContent: 'center', paddingBottom: 84 },
  tabPager: { flex: 1, overflow: 'hidden' },
  tabPagerTrack: { flex: 1, flexDirection: 'row' },
  tabPage: { flex: 1 },
  content: { gap: 10, padding: 12, paddingBottom: 96 },
  summaryCard: {
    alignItems: 'center',
    backgroundColor: theme.card,
    borderRadius: 8,
    paddingBottom: 16,
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  summaryBudgetInfo: { alignSelf: 'stretch', gap: 4, paddingBottom: 4 },
  summaryBudgetName: { color: theme.text, fontSize: 17, fontWeight: '900' },
  summaryBudgetCategory: { color: theme.textMuted, fontSize: 12, fontWeight: '800' },
  gaugeWrap: { height: 138, justifyContent: 'flex-end', marginBottom: -6 },
  summaryCaption: { color: theme.textSubtle, fontSize: 13, fontWeight: '700', marginTop: -40 },
  remainingValue: { color: theme.primary, fontSize: 28, fontWeight: '900', marginTop: 8 },
  dangerText: { color: theme.dangerText },
  summaryStats: { flexDirection: 'row', marginTop: 18, width: '100%' },
  summaryMetric: {
    alignItems: 'center',
    borderRightColor: theme.borderStrong,
    borderRightWidth: 1,
    flex: 1,
    gap: 4,
  },
  summaryMetricValue: { color: theme.text, fontSize: 13, fontWeight: '900' },
  summaryMetricLabel: { color: theme.textMuted, fontSize: 11, fontWeight: '700' },
  createButton: {
    alignItems: 'center',
    backgroundColor: theme.primary,
    borderRadius: 18,
    justifyContent: 'center',
    marginTop: 16,
    minHeight: 38,
    minWidth: 142,
    paddingHorizontal: 20,
  },
  createButtonText: { color: theme.textInverse, fontSize: 14, fontWeight: '900' },
  categoryBudgetCard: {
    alignItems: 'center',
    backgroundColor: theme.card,
    borderColor: theme.card,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  categoryBudgetCardSelected: { borderColor: theme.primary },
  swipeBudgetRow: {
    backgroundColor: theme.danger,
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  swipeBudgetContent: { width: '100%' },
  swipeDeleteBackground: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  swipeDeleteIcon: { color: theme.textInverse, fontSize: 28, fontWeight: '900' },
  budgetIcon: {
    alignItems: 'center',
    backgroundColor: theme.iconBubble,
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  budgetIconText: { color: theme.textInverse, fontSize: 17, fontWeight: '900' },
  budgetInfo: { flex: 1, gap: 7 },
  budgetTopRow: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  budgetName: { color: theme.text, flex: 1, fontSize: 15, fontWeight: '900' },
  budgetAmount: { color: theme.text, fontSize: 14, fontWeight: '900' },
  budgetCategory: { color: theme.textMuted, flex: 1, fontSize: 12, fontWeight: '700' },
  budgetRemaining: { color: theme.textSoft, fontSize: 12, fontWeight: '700' },
  progressTrack: { backgroundColor: theme.progressTrack, borderRadius: 3, height: 6, overflow: 'hidden' },
  progressFill: { backgroundColor: theme.primary, borderRadius: 3, height: '100%' },
  progressMeta: { color: theme.textSubtle, fontSize: 11, fontWeight: '700', textAlign: 'right' },
  budgetStatus: { fontSize: 12, fontWeight: '900' },
  budgetStatusActive: { color: theme.primary },
  budgetStatusExpired: { color: theme.textSubtle },
  transactionCopy: { flex: 1, gap: 3 },
  transactionDescription: { color: theme.text, fontSize: 13, fontWeight: '700' },
  transactionDate: { color: theme.textSubtle, fontSize: 11, fontWeight: '700' },
  transactionAmount: { color: theme.dangerText, fontSize: 13, fontWeight: '900' },
  emptyTransactionText: { color: theme.textSubtle, fontSize: 12, fontWeight: '700', lineHeight: 18 },
  transactionPanel: {
    backgroundColor: theme.card,
    borderRadius: 8,
    gap: 10,
    padding: 14,
  },
  detailTitle: { color: theme.text, fontSize: 15, fontWeight: '900' },
  dailySpendingRow: {
    alignItems: 'center',
    borderTopColor: theme.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingTop: 12,
  },
  todayBadge: {
    alignSelf: 'center',
    backgroundColor: theme.cardAlt,
    borderRadius: 2,
    marginTop: -3,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  todayBadgeText: { color: theme.textMuted, fontSize: 10, fontWeight: '800' },
  bottomSheetOverlay: {
    backgroundColor: theme.overlay,
    flex: 1,
    justifyContent: 'flex-end',
  },
  dayTransactionsSheet: {
    backgroundColor: theme.sheet,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    maxHeight: '72%',
    paddingBottom: 20,
  },
  sheetHeader: {
    alignItems: 'center',
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 68,
    paddingHorizontal: 18,
  },
  sheetTitle: { color: theme.text, fontSize: 18, fontWeight: '900' },
  sheetSubtitle: { color: theme.textMuted, fontSize: 12, fontWeight: '700', marginTop: 3 },
  sheetClose: { color: theme.primary, fontSize: 14, fontWeight: '900' },
  sheetTransactionList: { gap: 10, padding: 16 },
  sheetTransactionRow: {
    alignItems: 'center',
    borderBottomColor: theme.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingBottom: 10,
  },
  formScreen: { backgroundColor: theme.screen, flex: 1 },
  formHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 54,
  },
  formClose: { color: theme.text, fontSize: 34, fontWeight: '300', lineHeight: 36 },
  formTitle: { color: theme.text, fontSize: 20, fontWeight: '900' },
  formSave: { color: theme.primary, fontSize: 14, fontWeight: '900', textTransform: 'uppercase' },
  disabledText: { opacity: 0.5 },
  formContent: { gap: 18, padding: 18, paddingBottom: 56 },
  field: { gap: 8 },
  label: { color: theme.text, fontSize: 13, fontWeight: '800' },
  input: {
    backgroundColor: theme.card,
    borderColor: theme.border,
    borderRadius: 8,
    borderWidth: 1,
    color: theme.text,
    fontSize: 16,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  categoryList: { gap: 8 },
  categoryChip: {
    backgroundColor: theme.card,
    borderColor: theme.border,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  categoryChipSelected: { backgroundColor: theme.primary, borderColor: theme.primary },
  categoryChipText: { color: theme.textSoft, fontSize: 13, fontWeight: '800' },
  categoryChipTextSelected: { color: theme.textInverse },
  formRow: { flexDirection: 'row', gap: 12 },
  formRowItem: { flex: 1 },
  recurringRow: {
    alignItems: 'center',
    backgroundColor: theme.card,
    borderColor: theme.border,
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  helperText: { color: theme.textSubtle, fontSize: 11, fontWeight: '700', marginTop: 4 },
  fullCreateButton: {
    alignItems: 'center',
    backgroundColor: theme.primary,
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 50,
  },
  buttonDisabled: { opacity: 0.65 },
  });
}
