import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: { backgroundColor: '#020204', flex: 1 },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 54,
  },
  title: { color: '#fff', fontSize: 18, fontWeight: '800' },
  headerAddButton: {
    alignItems: 'center',
    backgroundColor: '#31c452',
    borderRadius: 18,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  headerAddText: { color: '#fff', fontSize: 26, fontWeight: '500', lineHeight: 29 },
  headerSpacer: { width: 36 },
  periodTabs: {
    borderBottomColor: '#303039',
    borderBottomWidth: 1,
    flexDirection: 'row',
    marginTop: 22,
  },
  periodTabButton: { minWidth: 108 },
  periodTabButtonActive: { minWidth: 120 },
  periodTabActive: {
    borderBottomColor: '#c7c8cc',
    borderBottomWidth: 2,
    color: '#fff',
    fontSize: 14,
    fontWeight: '800',
    paddingBottom: 12,
    paddingHorizontal: 18,
    minWidth: 120,
    textAlign: 'center',
  },
  periodTab: {
    color: '#8e9199',
    fontSize: 14,
    fontWeight: '800',
    minWidth: 108,
    paddingBottom: 12,
    paddingHorizontal: 18,
    textAlign: 'center',
  },
  loadingState: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  emptyState: { alignItems: 'center', flex: 1, justifyContent: 'center', paddingBottom: 84 },
  tabPager: { flex: 1, overflow: 'hidden' },
  tabPagerTrack: { flex: 1, flexDirection: 'row' },
  tabPage: { flex: 1 },
  content: { gap: 10, padding: 12, paddingBottom: 96 },
  summaryCard: {
    alignItems: 'center',
    backgroundColor: '#1e1e1f',
    borderRadius: 8,
    paddingBottom: 16,
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  summaryBudgetInfo: { alignSelf: 'stretch', gap: 4, paddingBottom: 4 },
  summaryBudgetName: { color: '#fff', fontSize: 17, fontWeight: '900' },
  summaryBudgetCategory: { color: '#9ca0aa', fontSize: 12, fontWeight: '800' },
  gaugeWrap: { height: 138, justifyContent: 'flex-end', marginBottom: -6 },
  summaryCaption: { color: '#8e9199', fontSize: 13, fontWeight: '700', marginTop: -40 },
  remainingValue: { color: '#31c452', fontSize: 28, fontWeight: '900', marginTop: 8 },
  dangerText: { color: '#ff6262' },
  summaryStats: { flexDirection: 'row', marginTop: 18, width: '100%' },
  summaryMetric: {
    alignItems: 'center',
    borderRightColor: '#3a3d43',
    borderRightWidth: 1,
    flex: 1,
    gap: 4,
  },
  summaryMetricValue: { color: '#fff', fontSize: 13, fontWeight: '900' },
  summaryMetricLabel: { color: '#9ca0aa', fontSize: 11, fontWeight: '700' },
  createButton: {
    alignItems: 'center',
    backgroundColor: '#31c452',
    borderRadius: 18,
    justifyContent: 'center',
    marginTop: 16,
    minHeight: 38,
    minWidth: 142,
    paddingHorizontal: 20,
  },
  createButtonText: { color: '#fff', fontSize: 14, fontWeight: '900' },
  categoryBudgetCard: {
    alignItems: 'center',
    backgroundColor: '#1e1e1f',
    borderColor: '#1e1e1f',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
  },
  categoryBudgetCardSelected: { borderColor: '#31c452' },
  swipeBudgetRow: {
    backgroundColor: '#d83b3b',
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  swipeBudgetContent: { width: '100%' },
  swipeDeleteBackground: {
    alignItems: 'center',
    bottom: 0,
    justifyContent: 'center',
    position: 'absolute',
    right: 0,
    top: 0,
    width: '100%',
  },
  swipeDeleteIcon: { color: '#fff', fontSize: 28, fontWeight: '900' },
  budgetIcon: {
    alignItems: 'center',
    backgroundColor: '#314c5d',
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  budgetIconText: { color: '#fff', fontSize: 17, fontWeight: '900' },
  budgetInfo: { flex: 1, gap: 7 },
  budgetTopRow: { alignItems: 'center', flexDirection: 'row', gap: 10, justifyContent: 'space-between' },
  budgetName: { color: '#fff', flex: 1, fontSize: 15, fontWeight: '900' },
  budgetAmount: { color: '#fff', fontSize: 14, fontWeight: '900' },
  budgetCategory: { color: '#9ca0aa', flex: 1, fontSize: 12, fontWeight: '700' },
  budgetRemaining: { color: '#b9bbc2', fontSize: 12, fontWeight: '700' },
  progressTrack: { backgroundColor: '#393c43', borderRadius: 3, height: 6, overflow: 'hidden' },
  progressFill: { backgroundColor: '#31c452', borderRadius: 3, height: '100%' },
  progressMeta: { color: '#8e9199', fontSize: 11, fontWeight: '700', textAlign: 'right' },
  budgetStatus: { fontSize: 12, fontWeight: '900' },
  budgetStatusActive: { color: '#31c452' },
  budgetStatusExpired: { color: '#8e9199' },
  transactionCopy: { flex: 1, gap: 3 },
  transactionDescription: { color: '#f4f6f8', fontSize: 13, fontWeight: '700' },
  transactionDate: { color: '#8e9199', fontSize: 11, fontWeight: '700' },
  transactionAmount: { color: '#ff6262', fontSize: 13, fontWeight: '900' },
  emptyTransactionText: { color: '#8e9199', fontSize: 12, fontWeight: '700', lineHeight: 18 },
  transactionPanel: {
    backgroundColor: '#1e1e1f',
    borderRadius: 8,
    gap: 10,
    padding: 14,
  },
  detailTitle: { color: '#fff', fontSize: 15, fontWeight: '900' },
  dailySpendingRow: {
    alignItems: 'center',
    borderTopColor: '#303039',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingTop: 12,
  },
  todayBadge: {
    alignSelf: 'center',
    backgroundColor: '#303039',
    borderRadius: 2,
    marginTop: -3,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  todayBadgeText: { color: '#9ca0aa', fontSize: 10, fontWeight: '800' },
  bottomSheetOverlay: {
    backgroundColor: 'rgba(0, 0, 0, 0.58)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  dayTransactionsSheet: {
    backgroundColor: '#1e1e1f',
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    maxHeight: '72%',
    paddingBottom: 20,
  },
  sheetHeader: {
    alignItems: 'center',
    borderBottomColor: '#303039',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 68,
    paddingHorizontal: 18,
  },
  sheetTitle: { color: '#fff', fontSize: 18, fontWeight: '900' },
  sheetSubtitle: { color: '#9ca0aa', fontSize: 12, fontWeight: '700', marginTop: 3 },
  sheetClose: { color: '#31c452', fontSize: 14, fontWeight: '900' },
  sheetTransactionList: { gap: 10, padding: 16 },
  sheetTransactionRow: {
    alignItems: 'center',
    borderBottomColor: '#303039',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    paddingBottom: 10,
  },
  formScreen: { backgroundColor: '#020204', flex: 1 },
  formHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 18,
    paddingTop: 54,
  },
  formClose: { color: '#fff', fontSize: 34, fontWeight: '300', lineHeight: 36 },
  formTitle: { color: '#fff', fontSize: 20, fontWeight: '900' },
  formSave: { color: '#31c452', fontSize: 14, fontWeight: '900', textTransform: 'uppercase' },
  disabledText: { opacity: 0.5 },
  formContent: { gap: 18, padding: 18, paddingBottom: 56 },
  field: { gap: 8 },
  label: { color: '#f4f6f8', fontSize: 13, fontWeight: '800' },
  input: {
    backgroundColor: '#1e1e1f',
    borderColor: '#303039',
    borderRadius: 8,
    borderWidth: 1,
    color: '#fff',
    fontSize: 16,
    paddingHorizontal: 14,
    paddingVertical: 13,
  },
  categoryList: { gap: 8 },
  categoryChip: {
    backgroundColor: '#1e1e1f',
    borderColor: '#303039',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  categoryChipSelected: { backgroundColor: '#31c452', borderColor: '#31c452' },
  categoryChipText: { color: '#c8cbd2', fontSize: 13, fontWeight: '800' },
  categoryChipTextSelected: { color: '#fff' },
  formRow: { flexDirection: 'row', gap: 12 },
  formRowItem: { flex: 1 },
  recurringRow: {
    alignItems: 'center',
    backgroundColor: '#1e1e1f',
    borderColor: '#303039',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
  },
  helperText: { color: '#8e9199', fontSize: 11, fontWeight: '700', marginTop: 4 },
  fullCreateButton: {
    alignItems: 'center',
    backgroundColor: '#31c452',
    borderRadius: 8,
    justifyContent: 'center',
    minHeight: 50,
  },
  buttonDisabled: { opacity: 0.65 },
});
